model:
    name: 'VelSupModel'
    depth_net:
        name: 'DPT'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    test:
        dataset: ['KITTI']
        path: ['/raid/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
save:
    folder: './save'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
