model:
    name: 'VelSupModel'
    optimizer:
        name: 'AdamW'
        depth:
            lr: 1e-5
        pose:
            lr: 1e-4
    scheduler:
        name: 'StepLR'
        step_size: 18
        gamma: 0.5
    depth_net:
        name: 'DPT'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
    loss:
        supervised_method : 'sparse-berhu'
        num_scales: 1
        supervised_num_scales : 1
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']

# # ##########################original setting########################
# wandb:
#     dry_run: False                        # Wandb dry-run (not logging)
#     name: 'swin_skipadd_v1.4'                                      # Wandb run name
#     project: "Swin_ablation"  # Wandb project
#     entity: "jmshin"    # Wandb entity
#     tags: []                                      # Wandb tags
#     dir: './' 
# model:
#     name: 'VelSupModel'
#     optimizer:
#         name: 'AdamW'
#         depth:
#             lr: 0.00006
#         pose:
#             lr: 0.0002
#     scheduler:
#         name: 'StepLR'
#         step_size: 20
#         gamma: 0.5
#     depth_net:
#         name: 'DPT'
#         version: '1A'
#     pose_net:
#         name: 'PoseNet'
#         version: ''
#     params:
#         crop: 'garg'
#         min_depth: 0.0
#         max_depth: 80.0
#     loss:
#         supervised_method : 'sparse-berhu'
#         num_scales: 4
#         supervised_num_scales : 1
# datasets:
#     augmentation:
#         image_shape: (192, 640)
#     train:
#         batch_size: 4
#         dataset: ['KITTI']
#         path: ['/data/datasets/KITTI_raw']
#         split: ['data_splits/eigen_zhou_files.txt']
#         depth_type: ['velodyne']
#         repeat: [1]
#     validation:
#         dataset: ['KITTI']
#         path: ['/data/datasets/KITTI_raw']
#         split: ['data_splits/eigen_test_files.txt']
#         depth_type: ['velodyne']
#     test:
#         dataset: ['KITTI']
#         path: ['/data/datasets/KITTI_raw']
#         split: ['data_splits/eigen_test_files.txt']
#         depth_type: ['velodyne']